name: Check / PR Comment Trigger

on:
  pull_request:
    types:
      - opened
      - reopened
  issue_comment:
    types:
      - created

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-comment:
    name: Check Comment
    runs-on: ubuntu-latest
    steps:
      - name: Generate App Token
        uses: tibdex/github-app-token@v1.9.0
        id: generate-token
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - uses: xt0rted/pull-request-comment-branch@v1
        id: comment-branch

      - name: Check Comment
        uses: Khan/pull-request-comment-trigger@v1.1.0
        id: check
        with:
          trigger: "!refresh"
          reaction: "rocket"
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}

      - name: Check Lokalise Update
        run: |
          echo "${{ steps.check.outputs.triggered == 'true' }}"
          echo "${{ steps.comment-branch.outputs.head_ref }}"

      # - uses: agilepathway/label-checker@v1.2.6
      #   with:
      #     repo_token: ${{ steps.generate-token.outputs.token }}
      #     any_of: ${{ steps.get_category_labels.outputs.result }}
      #     none_of: merge/blocked

      # - if: ${{ always() }}
      #   uses: lucaslim/find-comment@main
      #   id: fc
      #   with:
      #     token: ${{ steps.generate-token.outputs.token }}
      #     issue-number: ${{ github.event.pull_request.number }}
      #     comment-author: 'edealer-automation-bot[bot]'
      #     body-includes: The pull request is missing some mandatory labels
      #     direction: last

      # - if: ${{ failure() }}
      #   uses: peter-evans/create-or-update-comment@v2
      #   with:
      #     token: ${{ steps.generate-token.outputs.token }}
      #     comment-id: ${{ steps.fc.outputs.comment-id }}
      #     issue-number: ${{ github.event.pull_request.number }}
      #     body: |
      #       Hello @${{ github.actor }}

      #       The pull request is missing some mandatory labels. Please add one of the `category/<type>` labels to this pull request.

      #       **For more information, please refer to our [Pull Request Label Guidelines][1].**

      #       [1]: https://einc.atlassian.net/wiki/spaces/ED/pages/936640525/Pull+Requests#Labels
      #     edit-mode: replace

      # - if: ${{ success() && steps.fc.outputs.comment-node-id != '' }}
      #   continue-on-error: true
      #   uses: actions/github-script@v6.3.3
      #   with:
      #     github-token: ${{ steps.generate-token.outputs.token }}
      #     script: |
      #       const mutation = `
      #         mutation minimizeComment($id: ID!) {
      #             minimizeComment(input: { classifier: RESOLVED, subjectId: $id }) {
      #                 clientMutationId
      #             }
      #         }`;

      #       const variables = { id: '${{ steps.fc.outputs.comment-node-id }}' };
      #       await github.graphql(mutation, variables);
