name: Test Slack Notification

on: workflow_dispatch

jobs:
  test-e2e:
    runs-on: ubuntu-latest
    outputs:
      pipelineId: "${{ fromJSON(steps.cypress-test.outputs.response).id }}"
    steps:
      - name: Run Unit and End-to-End
        id: cypress-test
        uses: fjogeleit/http-request-action@v1
        with:
          url: "https://circleci.com/api/v2/project/gh/carmigo/edealer-web-v2/pipeline"
          method: "POST"
          customHeaders: >-
            {
              "x-attribution-login": "${{ github.actor }}",
              "x-attribution-actor-id": "${{ github.actor }}",
              "Circle-Token": "${{ secrets.CIRCLECI_TOKEN }}"
            }
          data: >-
            {
              "branch": "master",
              "parameters": {
                "appEnv": "dev",
                "event": "${{ github.event_name }}",
                "reason": "Manual"
              }
            }

      # - name: Show Response
      #   run: |
      #     echo '${{ fromJSON(steps.cypress-test.outputs.response).id }}'
      #     echo '${{ fromJSON(steps.cypress-test.outputs.response) }}'

  check-status:
    runs-on: ubuntu-latest
    needs: test-e2e
    outputs:
      circleStatus: ${{ steps.check-status.outputs.result }}
    steps:
      - uses: actions/checkout@v3.6.0
      - uses: actions/setup-node@v3.8.2
        with:
          node-version: 16
      - run: npm install p-wait-for@5.0.0 axios@1.1.2
      - id: check-status
        env:
          PIPELINE_ID: ${{ needs.test-e2e.outputs.pipelineId }}
          CIRCLECI_TOKEN: ${{ secrets.CIRCLECI_TOKEN }}
        uses: actions/github-script@v6
        with:
          result-encoding: json
          script: |
            const axios = require("axios");
            const { default: pWaitFor } = await import("${{ github.workspace }}/node_modules/p-wait-for/index.js");

            const { PIPELINE_ID, CIRCLECI_TOKEN } = process.env;

            const circleResponse = await pWaitFor(
              async () => {
                const response = await axios.get(
                  `https://circleci.com/api/v2/pipeline/${PIPELINE_ID}/workflow`,
                  {
                    headers: {
                      "x-attribution-login": "lucaslim",
                      "x-attribution-actor-id": "lucaslim",
                      "Circle-Token": CIRCLECI_TOKEN,
                    },
                  }
                );

                const status = response.data.items[0].status;
                if (status === "running") {
                  return false;
                } else {
                  return true && pWaitFor.resolveWith({
                    pipelineNumber: response.data.items[0].pipeline_number,
                    status: response.data.items[0].status,
                  });
                }
              },
              {
                interval: 2000,
                timeout: {
                  milliseconds: 900000,
                },
              }
            );

            return circleResponse;

  test-notify:
    runs-on: ubuntu-latest
    needs: check-status
    steps:
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_USERNAME: EDealer Release
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_ICON: https://i.ibb.co/NjrgqSk/EDealer-E.png
          MSG_MINIMAL: true
          SLACK_TITLE: " "
          SLACK_MESSAGE: |
            <!channel>

            :rocket: *WEB :spider_web: PRE-RELEASE v7.8.0 IS ON STAGE* :rocket: :this-is-fine:

            _${{ fromJSON(needs.check-status.outputs.circleStatus).status == 'success' && 'All test passed ✅ ' || 'One or more test had failed ⛔️' }} - <https://app.circleci.com/pipelines/github/carmigo/edealer-web-v2/${{ fromJSON(needs.check-status.outputs.circleStatus).pipelineNumber }} | view pipeline>_

            <https://github.com/carmigo/edealer-web-v2/releases/tag/7.8.0 | See release notes>
      # - name: slack-send
      #   uses: slackapi/slack-github-action@v1.22.0
      #   with:
      #     payload: |
      #       {
      #         "attachments": [
      #           {
      #             "color": "#2eb886",
      #             "blocks": [
      #               {
      #                 "type": "context",
      #                 "elements": [
      #                   {
      #                     "type": "image",
      #                     "image_url": "https://slack-imgs.com/?c=1&o1=wi128.he128.si&url=https%3A%2F%2Fgithub.com%2Flucaslim.png%3Fsize%3D128",
      #                     "alt_text": "lucaslim"
      #                   },
      #                   {
      #                     "type": "mrkdwn",
      #                     "text": "*<https://www.github.com/lucaslim|lucaslim>*"
      #                   }
      #                 ]
      #               },
      #               {
      #                 "type": "context",
      #                 "elements": [
      #                   {
      #                     "type": "mrkdwn",
      #                     "text": "<!channel>"
      #                   }
      #                 ]
      #               },
      #               {
      #                 "type": "context",
      #                 "elements": [
      #                   {
      #                     "type": "mrkdwn",
      #                     "text": ":rocket: *WEB :spider_web: PRE-RELEASE v7.8.0 IS ON STAGE* :rocket: :this-is-fine:"
      #                   }
      #                 ]
      #               },
      #               {
      #                 "type": "context",
      #                 "elements": [
      #                   {
      #                     "type": "mrkdwn",
      #                     "text": " "
      #                   }
      #                 ]
      #               },
      #               {
      #                 "type": "context",
      #                 "elements": [
      #                   {
      #                     "type": "mrkdwn",
      #                     "text": "<https://github.com/${{ github.repository }}/releases/tag/${{ github.event.release.tag_name }} | See release notes>"
      #                   }
      #                 ]
      #               }
      #             ]
      #           }
      #         ]
      #       }
