name: Notify 🔊

on:
  workflow_call:
    inputs:
      message:
        required: true
        type: string
      includeActor:
        required: false
        type: boolean
        default: true
      asAttachment:
        required: false
        type: boolean
        default: false
      color:
        required: false
        type: string
        default: good
      threadId:
        required: false
        type: string
    outputs:
      ts:
        value: ${{ jobs.slack.outputs.ts }}
      thread_ts:
        value: ${{ jobs.slack.outputs.thread_ts }}

jobs:
  slack:
    name: 💬 Send Message to Slack 🚀
    runs-on: ubuntu-latest
    env:
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_USER_OAUTH_ACCESS_TOKEN }}
    outputs:
      ts: ${{ steps.slack-include-actor.outputs.ts || steps.slack.outputs.ts }}
      thread_ts: ${{ steps.slack-include-actor.outputs.thread_ts || steps.slack.outputs.thread_ts }}
    steps:
      - name: Preparing Slack Message
        id: prepare-slack-message
        run: |
          SLACK_MESSAGE="${{ inputs.message }}"
          SLACK_MESSAGE="$(echo "$SLACK_MESSAGE" | sed -z 's/\n/\\n/g')"
          echo "::set-output name=message::${SLACK_MESSAGE}"

      - name: Slack Notification (include Actor)
        id: slack-include-actor
        if: ${{ inputs.asAttachment }}
        uses: slackapi/slack-github-action@v1.26.0
        with:
          channel-id: C0461JBK90R
          payload: >-
            {
              ${{ inputs.threadId != '' && format('"thread_ts": "{0}",', inputs.threadId) || '' }}
              "attachments": [
                {
                  ${{ inputs.includeActor && format('"author_name": "{0}",', github.actor) || '' }}
                  ${{ inputs.includeActor && format('"author_link": "https://github.com/{0}",', github.actor) || '' }}
                  ${{ inputs.includeActor && format('"author_icon": "https://github.com/{0}.png?size=32",', github.actor) || '' }}
                  "color": "${{ inputs.color }}",
                  "fallback": "${{ steps.prepare-slack-message.outputs.message }}",
                  "fields": [
                    {
                      "title": "",
                      "short": false,
                      "value": "${{ steps.prepare-slack-message.outputs.message }}"
                    }
                  ]
                }
              ]
            }

      - name: Slack Notification
        id: slack
        if: ${{ !inputs.asAttachment }}
        uses: slackapi/slack-github-action@v1.26.0
        with:
          channel-id: C0461JBK90R
          payload: >-
            {
              ${{ inputs.threadId != '' && format('"thread_ts": "{0}",', inputs.threadId) || '' }}
              "text": "${{ steps.prepare-slack-message.outputs.message }}",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "${{ steps.prepare-slack-message.outputs.message }}"
                  }
                }
              ]
            }
